image: registry.it.hs-heilbronn.de/it/development/git-runners/itadmin-openjdk21_repo-hhnit:latest

stages:
  - tests
  - integration-test
  - bundle

swlab1-junit:
  stage: tests
  script:
    - mvn test

swlab1-budle:
  stage: bundle
  script:
    - mvn -Dskip.tests=true package
  artifacts:
    paths:
    - CtViewer/target/group6PipelineLATEST.jarT.jar
    expire_in: 5 minutes
